name: 'Build and Deploy'

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test

  build:
    runs-on: self-hosted
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./dist
